name: mernapp

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mernapp

  backend:
    build:
      context: ./server
      dockerfile: DockerFile
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mernapp
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: DockerFile
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mernapp
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  mernapp:
    driver: bridge
